<?php

namespace app\home\controller;

use think\Controller;
use think\Db;
use think\Request;
use think\Validate;

class Address extends Controller
{

    protected $userId;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->userId = session('home_user_id');
        $this->userId = 1;
    }


    /**
     * @return \think\response\Json
     * 收货地址列表
     */
    public function index()
    {
        $address = Db::table('sql_address')
            ->field('id,consignee,phone,province,city,area,detail,is_default')
            ->where('uid', $this->userId)
            ->order('is_default', 'desc')->select();
        return json(['data' => $address, 'msg' => '查询成功', 'code' => 200]);
    }


    /**
     * @param Request $request
     * @return \think\response\Json
     * 增加收货地址
     * 传入是否默认 is_default 0非默认 1默认
     */
    public function addAddr(Request $request)
    {
        $rule = [
            'consignee' => 'require|max:20',
            'phone' => 'require|/^1[34578]\d{9}$/',
            'province'=>'require|max:50',
            'city'=>'require|max:100',
            'area'=>'require|max:100',

        ];
        $msg = [
            'consignee.require' =>'收货人姓名不能为空',
            'consignee.max:20' =>'收货人姓名不能超过20个字符',
            'phone.require' => '手机号不能为空',
            'phone./^1[34578]\d{9}$/' => '手机号格式错误',
            'province.require'=>'省份不能为空',
            'province.max:50'=>'省份最多不能超过50个字符',
            'city.require'=>'城市不能为空',
            'city.max:100'=>'城市最多不能超过100个字符',
            'area.require'=>'区/县不能为空',
            'area.max:100'=>'区/县最多不能超过100个字符',
        ];
        $input = $request->post();
        $validate = new Validate($rule, $msg);
        if (!$validate->check($input)) {
            return json(['msg' => $validate->getError(), 'code' => 1001]);
        }
        $input['created_at'] = date('YmdHis');
        $res = Db::table('sql_address')->insert($input);
        if($res){
            return json(['msg' =>'添加成功', 'code' => 200]);
        }
        return json(['msg' =>'添加失败', 'code' => 1001]);
    }


    /**
     * @param Request $request
     * @return \think\response\Json
     * 编辑收货地址页面
     */
    public function webEditAddr(Request $request){
        $addrId = $request->param('addrId');
        if(empty($addrId)){
            return json(['msg'=>'参数错误','code'=>1001]);
        }
        $address = Db::table('sql_address')
            ->field('id,consignee,phone,province,city,area,detail')
            ->where('id',$addrId)->find();
        return json(['data'=>$address,'msg'=>'查询成功','code'=>200]);
    }


    /**
     * @param Request $request
     * @return \think\response\Json
     * @throws \think\Exception
     * 执行编辑收货地址
     */
    public function actEditAddr(Request $request){
        $rule = [
            'addrId' => 'require',
            'consignee' => 'max:20',
            'phone' => '/^1[34578]\d{9}$/',
            'province'=>'max:50',
            'city'=>'max:100',
            'area'=>'max:100',

        ];
        $msg = [
            'addrId.require' => '参数错误',
            'consignee.max:20' =>'收货人姓名不能超过20个字符',
            'phone./^1[34578]\d{9}$/' => '手机号格式错误',
            'province.max:50'=>'省份最多不能超过50个字符',
            'city.max:100'=>'城市最多不能超过100个字符',
            'area.max:100'=>'区/县最多不能超过100个字符',
        ];
        $input = $request->post();
        $validate = new Validate($rule, $msg);
        if (!$validate->check($input)) {
            return json(['msg' => $validate->getError(), 'code' => 1001]);
        }
        $input['updated_at'] = date('YmdHis');
        $res = Db::table('sql_address')->update($input);
        if($res){
            return json(['msg'=>'编辑成功','code'=>200]);
        }
        return json(['msg'=>'编辑失败','code'=>1002]);
    }





    /**
     * @param Request $request
     * 删除收货地址
     */
    public function delAddr(Request $request)
    {
        $addrId = $request->param('addrId');
        if (empty($addrId)) {
            return json(['msg' => '参数错误', 'code' => 1001]);
        }
        $addr = Db::table('sql_address')->where('id', $addrId)->find();
        if ($addr['is_default'] == 1) {
            return json(['msg' => '默认地址暂不能删除', 'code' => 1002]);
        }
        $res = Db::table('sql_address')->where('id', $addrId)->delete();
        if ($res) {
            return json(['msg' => '删除成功', 'code' => 200]);
        }
        return json(['msg' => '删除失败', 'code' => 200]);
    }

}