<?php

namespace app\home\controller;

use app\backsystem\controller\File;
use app\backsystem\model\AccountModel;
use app\backsystem\model\AddressModel;
use app\backsystem\model\ApplyModel;
use app\backsystem\model\UserModel;
use app\backsystem\model\VoucherModel;
use Service\MsgCode;
use think\Controller;
use think\Db;
use think\Exception;
use think\Loader;
use think\Request;

class Partner extends Base
{
    protected $userId;
    protected $cost;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->userId = session('home_user_id');
        //参数设置,从配置读取
        $config = file_get_contents('config');
        $conf = unserialize($config);
        $this->cost = $conf['comp'];
    }





    /**
     * @return \think\Response
     * 激活成为合伙人
     * 页面
     */
    public function index()
    {
        $user = UserModel::get($this->userId);
        //匹配报单中心id
        $prentId = getAgentId($user['address']['province'],$user['address']['city'],$user['address']['area']);

        $prent = UserModel::get($prentId);
        //组装参数
        $return = [];
        $return['wqcode'] = $prent['qcode']['wqcode'];
        $return['aqcode'] = $prent['qcode']['aqcode'];
        $return['phone'] = $prent['phone'];
        $return['cost'] = $this->cost;
        return json(['data'=>$return,'msg'=>'查询成功','code'=>200]);
    }





    /**
     * @return \think\Response
     * 点击提交,提交申请合伙人
     */
    public function actLive(Request $request)
    {
        $count = db('voucher')->where(['uid'=>$this->userId,'status'=>1])->count();
        if($count > 0){
            return json(['msg'=>'您已提交申请,请耐心等待','code'=>1002]);
        }
        $user = UserModel::get($this->userId);
        if($user['class'] >= 2){
            return json(['msg'=>'您已经是报单中心无需重复申请','code'=>1002]);
        }
        $file = $request->file('voucher');
        $data = [];
        if(isset($file)){
            $imgurl = File::upload($file);
            $data['img'] = $imgurl->getData()['data'];
        }
        //获取报单中心id
        $prentId = getAgentId($user['address']['province'],$user['address']['city'],$user['address']['area']);

        $data['uid'] = $this->userId;
        $data['actid'] = $prentId;         //激活id
        $data['status'] = 1;         //申请中
        $data['created_at'] = date('YmdHis');
        $res = VoucherModel::create($data);
        if(empty($res['img'])){
            VoucherModel::get($res['id'])->delete();
            return json(['msg'=>'提交失败','code'=>1001]);
        }
        return json(['msg'=>'提交成功','code'=>200]);
    }

    /**
     * @return \think\response\Json
     * 激活用户列表
     */
    public function memberList(){
        $lists = VoucherModel::all(function($query){
            $query->order('id','desc');
            $query->where(['actid'=>$this->userId,'status'=>1]);
        });
        $return = [];
        foreach($lists as $key=>$val){
            $return[$key]['id'] = $val['uid'];
            $return[$key]['headimgurl'] = $val['user']['headimgurl'];
            $return[$key]['nickname'] = $val['user']['nickname'];
            $return[$key]['phone'] = $val['user']['phone'];
            $return[$key]['created_at'] = $val['created_at'];
        }
        return json(['data'=>$return,'msg'=>'查询成功','code'=>200]);
    }



    /**
     * @param Request $request
     * 确认激活
     * 页面
     */
    public function sureActivate(Request $request){
        $downId = $request->param('downId');
        $downData = UserModel::get($downId);
        if(!$downData){
            return json(['msg'=>'参数错误','code'=>1001]);
        }
        $return = [];

        $return['down_phone'] = $downData['phone'];
        $return['voucher'] = db('voucher')->where(['status'=>1,'uid'=>$downData['id']])->value('img');
        $return['cost'] = $this->cost;
        $return['balance'] = UserModel::get($this->userId)['balance'];
        return json(['data'=>$return,'msg'=>'查询成功','code'=>200]);
    }

    /**
     * @param Request $request
     * 点击确认激活
     */
    public function actSureActivate(Request $request){
        $input = $request->post();
        $user = UserModel::get($this->userId);
//        if(!isset($input['password']) || md5($input['password']) !== $user['two_password']){
//            return json(['msg'=>'支付密码不正确','code'=>1001]);
//        }
        if($user['balance'] < $this->cost){
            return json(['msg'=>'余额不足','code'=>1002]);
        }
        if(empty($input['downId'])){
            return json(['msg'=>'参数错误','code'=>1002]);
        }
        $down = UserModel::get($input['downId']);
        if($down['class'] > 1){
            return json(['msg'=>'该用户已是合伙人,无需重复激活','code'=>1002]);
        }
        Db::startTrans();
        try{
            //扣除自己余额
            UserModel::get($this->userId)->setDec('balance',$this->cost);

            //增加余额扣除记录
            $list = AccountModel::getAccountData($this->userId,$this->cost,'激活合伙人',8,2,$down['id']);
            AccountModel::create($list);
            //返佣
            $rebate = new Rebate();
            $res = $rebate->partnerRebate($down['address'],$down['id']);
            //修改用户级别
            UserModel::get($down['id'])->save(['class'=>2,'actid'=>$this->userId]);
            //修改用户申请状态
            db('voucher')->where(['status'=>1,'uid'=>$down['id']])->update(['status'=>2]);
            //用户进入公排
            if(db('config')->where('id',1)->value('switch') == 1){
                $rebate = new Rebate();
                $rebate->superRebate($down['id'],$down['pid']);  //返佣- 直推奖
                $rebate->goQualifying($down['id'],$down['phone']);
            }
            Db::commit();
            return json(['msg'=>'激活成功','code'=>200]);
        }catch(Exception $e){
            Db::rollback();
            return json(['msg'=>$e->getMessage(),'code'=>1003]);
        }
    }


    /**
     * 拒绝用户激活
     */
    public function actRefuse(Request $request){
        $downId = $request->param('downId');
        if(empty($downId)){
            return json(['msg'=>'参数错误','code'=>1002]);
        }
        $res = db('voucher')->where(['uid'=>$downId,'status'=>1])->update(['status'=>3]);
        if($res){
            return json(['msg'=>'已拒绝用户','code'=>200]);
        }
        return json(['msg'=>'操作失败','code'=>1001]);
    }



    /**
     * @return \think\response\Json
     * 展示收款码
     */
    public function showReceivables(){
        $qcode = db('qcode')->where('uid',$this->userId)->find();
        return json(['data'=>$qcode,'msg'=>'查询成功','code'=>200]);
    }



    //上传收款码
    public function receivables(Request $request){       //需传入收款码qcode  支付宝收款码需传入 type=alipay
        $user = UserModel::get($this->userId);
        if($user['class'] < 3){
            return json(['msg'=>'级别不够','code'=>1002]);
        }
        $input = $request->post();
        $type = 'wqcode';
        if(isset($input['type']) && $input['type'] == 'alipay'){
            $type = 'aqcode';
        }
        $file = $request->file('qcode');
        $data = [];
        if(isset($file)){
            $imgurl = File::upload($file);
            $data[$type] = $imgurl->getData()['data'];
        }
        $data['uid'] = $this->userId;
        $data['created_at'] = date('YmdHis');

        if($codeId = db('qcode')->where('uid',$this->userId)->value('id')){
            $res = db('qcode')->where('id',$codeId)->update([$type=>$data[$type]]);
        }else{
            $res = db('qcode')->insert($data);
        }
        if($res){
            return json(['msg'=>'保存成功','code'=>200]);
        }
        return json(['msg'=>'保存失败','code'=>1001]);
    }




    /**
     *注册下级成为合伙人
     * 页面
     */
    public function registPartner()
    {
        $balance = UserModel::get($this->userId)['balance'];
        $return['cost'] = $this->cost;
        $return['balance'] = $balance;
        return json(['data'=>$return,'msg'=>'查询成功','cpde'=>200]);

    }

    /**
     * 点击注册
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function actRegister(Request $request)
    {
        $input = $request->post();
        $validate = Loader::validate('Users');
        if(!$validate->check($input)){
            return json(['msg'=>$validate->getError(),'code'=>1001]);
        }

        $code = $input['code'];
        $time = time() - 600;
        $codeData = db('code')->where(['phone'=>$input['phone'],'type'=>1,'status'=>1])->order('id','desc')->find();

        //TODO:获取验证码
        if($input['phone'] != $codeData['phone'] && $code != $codeData['code']){
            return json(['msg'=>'验证码不正确','code'=>1002]);
        }
        if(strtotime($codeData['created_at']) < $time ){
            return json(['msg'=>'验证码已失效,请重新获取','code'=>1010]);
        }
        $user = UserModel::get($this->userId);
        if(!isset($input['password']) || md5($input['password']) !== $user['two_password']){
            return json(['msg'=>'支付密码不正确','code'=>1003]);
        }
        if($user['balance'] < $this->cost){
            return json(['msg'=>'余额不足','code'=>1002]);
        }
        Db::startTrans();
        try{
            //扣除用户余额
            db('users')->where('id',$this->userId)->setDec('balance',$this->cost);

            //增加用户
            $userData = [];
            $falg = ['password'=>foo(6),'two_password'=>rand(100000,999999)];      //获取登陆密码支付密码
            $userData['pid'] = $this->userId;
            $userData['actid'] = $this->userId;
            $userData['phone'] = $input['phone'];
            $userData['headimgurl'] = config('back_domain').'/uploads/default.png';
            $userData['nickname'] = '用户'.$input['phone'];
            $userData['password'] = md5($falg['password']);
            $userData['two_password'] = md5($falg['two_password']);
            $userData['class'] = 2;
            $userData['created_at'] = date('YmdHis');
            $newUser = UserModel::create($userData);

            //增加余额消费记录
            $list = AccountModel::getAccountData($this->userId,$this->cost,'注册新合伙人',8,2,$newUser['id']);
            AccountModel::create($list);

            //激活合伙人-报单中心返佣(及余额记录)
            $rebate = new Rebate();
            $rebate->partnerRebate($input,$newUser['id']);
            //进入公排
            if(db('config')->where('id',1)->value('switch') == 1){
                $rebate->goQualifying($newUser['id'],$newUser['phone'],$this->userId);
            }
            //激活合伙人-上级报单中心返佣(及余额记录)
            $rebate->superRebate($newUser['id'],$this->userId,2);
            //增加用户地址
            $addr = [];
            $addr['uid'] = $newUser['id'];
            $addr['province'] = $input['province'];
            $addr['city'] = $input['city'];
            $addr['area'] = $input['area'];
            $addr['created_at'] = date('YmdHis');
            AddressModel::create($addr);
            //TODO:发送短信,告知用户账号密码
            $msg = new MsgCode();
            $msg->sendMsg($newUser['phone'],4,$falg);
                //验证码修改状态
            db('code')->where('id',$codeData['id'])->update(['status'=>2]);
             Db::commit();
            return json(['data'=>$newUser,'msg'=>'注册成功','code'=>200]);
        }catch(Exception $e){
            Db::rollback();
            return json(['msg'=>$e->getMessage(),'code'=>1004]);
        }
    }

    /**
     *
     *申请报单中心
     */
    public function applyCenter(Request $request)
    {
        if(db('apply')->where(['uid'=>$this->userId,'status'=>1])->count() >= 1){
            return json(['msg'=>'您已提交申请,请等待后台处理','code'=>1001]);
        }
        if(db('users')->where(['id'=>$this->userId])->value('class') < 2){
            return json(['msg'=>'您还不是合伙人,暂无法申请','code'=>1001]);
        }
        $input = $request->post();
        $validate = Loader::validate('Apply');
        if (!$validate->check($input)) {
            return json(['msg' => $validate->getError(), 'code' => 1001]);
        }
        $where = [];
        if ($input['level'] <= 5) {
            $where['province'] = $input['province'];
            $where['level'] = 5;
        }
        if ($input['level'] <= 4) {
            $where['city'] = $input['city'];
            $where['level'] = 4;
            if(empty($input['city'])){
                return json(['msg'=>'城市不能为空','code'=>1001]);
            }
        }
        if ($input['level'] == 3) {
            $where['area'] = $input['area'];
            $where['level'] = 3;
            if(empty($input['city']) || empty($input['area'])){
                return json(['msg'=>'城市和县/区都不能为空','code'=>1001]);
            }
        }
        $where['status'] = 2;
        $res1 = db('apply')->where($where)->count();
        if ($res1 >= 1) {
            return json(['msg' => '该地区已有报单中心,请选择其他地区', 'code' => 1002]);
        }

        $input['uid'] = $this->userId;
        $input['created_at'] = date('YmdHis');
        $res = ApplyModel::create($input);
        if ($res) {
            return json(['msg' => '申请报单中心成功', 'code' => 200]);
        }
    }





}
