<?php
namespace app\home\controller;



use app\backsystem\model\AddressModel;
use app\backsystem\model\RowModel;
use app\backsystem\model\UserModel;
use app\backsystem\model\UserRelationModel;
use think\Controller;
use think\Db;
use think\Request;

class Team extends Base{

    protected $userId;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->userId = session('home_user_id');
    }


    //我的团队
    public function index(Request $request){
        $page = $request->param('page',1);
        $list = 10;
        $page = ($page-1) * $list;

        $allUser = UserRelationModel::all(function($query)use($page,$list){
            $query->where('pid',$this->userId);
            $query->limit($page,$list);
            $query->order('id','desc');
        });

        $return = [];
        $key = 0;
        foreach($allUser as $key=>$val){
            $return[$key]['nickname'] = $val['user']['nickname'];
            $return[$key]['phone'] = $val['user']['phone'];
            $return[$key]['headimgurl'] = $val['user']['headimgurl'];
            $return[$key]['created_at'] = $val['user']['created_at'];
        }
        $totalNum = $key + 1;
        return json(['data'=>['return'=>$return,'totalNum'=>$totalNum],'msg'=>'查询成功','code'=>200]);
    }


    //地区新增会员
    public function newMember(){
        $user = UserModel::get($this->userId);
        if($user['class'] < 3){
            return json(['msg'=>'级别不够','code'=>200]);
        }

        $newData = UserModel::all(function($query){
            $query->order('id','desc');
            $query->where('class','>=',2);         //已激活会员
//            $query->where('id','in',$newAddr);
            $query->where('actid',$this->userId);
            $query->whereTime('created_at','month');
        });
        $return = [];
        $totalNum = 0;
        foreach($newData as $key=>$val){
            $totalNum += 1;
            $return[$key]['headimgurl'] = $val['headimgurl'];
            $return[$key]['nickname'] = $val['nickname'];
            $return[$key]['created_at'] = $val['created_at'];
            $return[$key]['act_phone'] = hideStar($val['acts']['phone']);
        }
        return json(['data'=>$return,'top'=>['totalNum'=>$totalNum,'time'=>date('Y年m月')],'msg'=>'查询成功','code'=>200]);
    }


    //我的小组
    public function mygroup(Request $request){
        $packageType = $request->param('type');        //传入需要查询的小组 ABC
        if(!in_array($packageType,['A','B','C'])){
            return json(['msg'=>'参数错误','code'=>1001]);
        }
        $row = 'sql_row'.$packageType;
        $user = Db::table($row)->where(['user_id'=>$this->userId])->order('id','desc')->find();
        if(!$user){
            return json(['msg'=>'暂未进入排位','code'=>1001]);
        }
        $rows = Db::table($row)->where('time',$user['time'])
            ->order('position','asc')->select();

        $theRound = Db::table($row)->where(['user_id'=>$this->userId,'position'=>1])->count();
        $return = [];
        foreach($rows as $key=>$val){
            $data = Db::table('sql_users')
                ->field('headimgurl,nickname')
                ->where('id',$val['user_id'])->find();
            $return[$key]['position'] = $val['position'];
            $return[$key]['headimgurl'] = $data['headimgurl'];
            $return[$key]['user_nickname'] = $data['nickname'];
            $return[$key]['created_at'] = $val['created_at'];
        }
        return json(['data'=>$return,'theRound'=>$theRound,'msg'=>'查询成功','code'=>200]);
    }




}




