<?php
namespace app\home\controller;



use app\backsystem\model\AddressModel;
use app\backsystem\model\RowModel;
use app\backsystem\model\UserModel;
use think\Controller;
use think\Request;

class Team extends Base{

    protected $userId;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->userId = session('home_user_id');
    }


    //我的团队
    public function index(Request $request){
       $type = $request->param('type');         //type = 1获取直推人员  type= 2 获取 间推人员
        $page = $request->param('page');
        $list = 10;
        $page = ($page-1) * $list;
        if(!in_array($type,[1,2])){
            return json(['msg'=>'参数错误','code'=>1001]);
        }
        if($type == 1){
            $allId = [$this->userId];
        }else{
            $allId = db('users')->where(['pid'=>$this->userId])->column('id');
        }
        $user = [];
        if($allId){
            $user = UserModel::all(function($query)use($allId,$page,$list){
                $query->order('id','desc');
                $query->limit($page,$list);
                $query->field('id,pid,nickname,phone,created_at,headimgurl');
                $query->where('pid','in',$allId);
            });
        }

        $return = [];
        $first = db('users')->where(['pid'=>$this->userId])->column('id');
        $totalNum = count($first);
        if($first){
            $totalNum = db('users')->where('pid','in',$first)->count() + count($first);
        }
        foreach ($user as $key => $val) {
            $return[$key]['nickname'] = $val['nickname'];
            $return[$key]['phone'] = $val['phone'];
            $return[$key]['created_at'] = $val['created_at'];
            $return[$key]['headimgurl'] = $val['headimgurl'];
        }
        return json(['data'=>['return'=>$return,'id'=>$allId,'totalNum'=>$totalNum],'msg'=>'查询成功','code'=>200]);
    }


    //地区新增会员
    public function newMember(){
        $user = UserModel::get($this->userId);
        if($user['class'] < 3){
            return json(['msg'=>'级别不够','code'=>200]);
        }
        $where = [];
//        $apply = db('apply')->where(['uid'=>$this->userId,'status'=>2])->find();
//        if($user['class'] <= 5){
//            $where['province'] = $apply['province'];
//        }
//        if($user['class'] <= 4){
//            $where['city'] = $apply['city'];
//        }
//        if($user['class'] == 3){
//            $where['area'] = $apply['area'];
//        }
//        $where['uid'] = ['neq',$this->userId];
//        $newAddr = db('address')->where($where)->column('uid');          //获取地区内会员id
//        $newAddr = objToArray($newAddr);
        $newData = UserModel::all(function($query){
            $query->order('id','desc');
            $query->where('class','>=',2);         //已激活会员
//            $query->where('id','in',$newAddr);
            $query->where('actid',$this->userId);
            $query->whereTime('created_at','month');
        });
        $return = [];
        $totalNum = 0;
        foreach($newData as $key=>$val){
            $totalNum += 1;
            $return[$key]['headimgurl'] = $val['headimgurl'];
            $return[$key]['nickname'] = $val['nickname'];
            $return[$key]['created_at'] = $val['created_at'];
            $return[$key]['act_phone'] = hideStar($val['acts']['phone']);
        }
        return json(['data'=>$return,'top'=>['totalNum'=>$totalNum,'time'=>date('Y年m月')],'msg'=>'查询成功','code'=>200]);
    }


    //我的小组
    public function mygroup(){
        $user = db('row')->where(['user_id'=>$this->userId])->order('id','desc')->find();
        if(!$user){
            return json(['msg'=>'暂未进入排位','code'=>1001]);
        }
        $row = RowModel::all(function($query)use($user){
            $query->order('position','asc');
            $query->where('time',$user['time']);
        });
        $theRound = db('row')->where(['user_id'=>$this->userId,'position'=>1])->count();
        $return = [];
        foreach($row as $key=>$val){
            $return[$key]['position'] = $val['position'];
            $return[$key]['headimgurl'] = $val['user']['headimgurl'];
            $return[$key]['user_nickname'] = $val['user']['nickname'];
            $return[$key]['created_at'] = $val['created_at'];
        }
        return json(['data'=>$return,'theRound'=>$theRound,'msg'=>'查询成功','code'=>200]);
    }




}




